version: "3.9"

services:
  flask:
    build: api/
    networks:
      - docker_default
    ports:
      - "50:50"
    depends_on:
      - db
    container_name: flask
    volumes:
      - db-data:/data/
    command: flask --app run init-db

  db:
    build: data/
    volumes:
      - db-data:/data/
    container_name: db

volumes:
  db-data:

networks:
  docker_default:
    driver: bridge
