version: "3.9"

services:
  flask:
    build: api/
    networks:
      - docker_default
    ports:
      - "50:50"
    container_name: flask
    command: flask --app run init-db
    depends_on:
      - db

  db:
    build: data/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - docker_default

networks:
  docker_default:
    driver: bridge
