version: '9'

services:
  flask:
    build: api/
    networks:
      - docker1_default
    ports:
      - "50:50"
    depends_on:
      - db
    container_name: flask
    volumes:
      - db-data:/data/
    command: flask --app run init-db

  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes:
      - db-data:/data/
    container_name: db

volumes:
  db-data:

networks:
  docker1_default:
    driver: bridge
