version: '6'

services:
  flask:
    build: api/
    networks:
      - docker1_default
    ports:
      - "50:5050"
    container_name: flask
    command: flask --app run run --debug

  npm:
    build: front/
    networks:
      - docker1_default
    ports:
      - "5000:5000"
    container_name: npm
    command: npm run start

networks:
  docker1_default:
    driver: bridge
